# Copyright (c) 2019-2020 Yoann MOUGNIBAS
#
# This file is part of LazyCook.
#
# LazyCook is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LazyCook is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LazyCook.  If not, see <https://www.gnu.org/licenses/>.

# Trigger a build on any branch
#trigger:
#- master

# ----------------------------------------------------
# Use this Microsoft based agent (ubuntu LTS release)
# ----------------------------------------------------
pool:
  vmImage: 'ubuntu-18.04'

# ------------------
# Pipeline's stages
# ------------------
stages:

  # Build stage
  # Use ".NET Core CLI" task
  - stage : build_stage
    jobs:
      - job: build_job
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              arguments: '--configuration Release'
            name: 'build_step'

  # Test stage
  # Use ".NET Core CLI" task
  # Test results will be automatically published (discovered as ".trx" file format)
  # Code coverage results need to be published using dedicated "Publish Code Coverage Results" task
  - stage: test_stage
    jobs:
      - job: test_job
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              arguments: '--configuration Release --logger trx'
            name: 'test_step'
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/CoverageResults/coverage.cobertura.xml'
